-- V4 -- where an insight came from.
--
-- Insights are now generated by the agent from the warehouse and synced in. The seed
-- rows predate that and are still useful as a fallback when the agent is down, so the
-- sync has to be able to remove its own stale output without touching anything else.
-- Without this column the only options are "delete everything for the tenant" (which
-- takes the seed and its action drafts with it, via ON DELETE CASCADE) or "never delete"
-- (which leaves a metric that has recovered sitting on the dashboard forever).

ALTER TABLE insight
    ADD COLUMN source VARCHAR(16) NOT NULL DEFAULT 'seed';

ALTER TABLE insight
    ADD CONSTRAINT ck_insight_source CHECK (source IN ('seed', 'agent'));

-- The sync's own query: everything it wrote for this tenant, to diff against what the
-- agent just returned.
CREATE INDEX ix_insight_tenant_source ON insight (tenant_id, source);

COMMENT ON COLUMN insight.source IS
    'seed = demo fixture loaded from db/seed; agent = generated from the warehouse by the detection pass';
